add contact page
Tejashri-Taral/TrendTrove-Ecommerce pull request #17
Opened 2024-10-01 17:17 UTC by Gauravtb2253

I have added the contact page 
Check it

Thank you

2024-10-01 19:06 UTC, Tejashri-Taral requested changes
Great work!
Can you please add the link in the footer too.

2024-10-02 05:52 UTC, Gauravtb2253 commented
I have added the links pls check it

2024-10-02 07:57 UTC, vishesh1525 commented
Hey can i make some more improvements in the contact section if you assign me the issue 
by sending direct sudden emails to the users that we will be available soon and improving the UI also

2024-10-02 13:16 UTC, Tejashri-Taral approved these changes

2024-10-02 13:19 UTC, merged