Issue resolved#253 added save & share buttons
Tejashri-Taral/TrendTrove-Ecommerce pull request #328
Opened 2024-10-12 11:02 UTC by KrishnaMohanty08

added save and share buttons with the appropriate styling and features.The share options help the user to share the links to socials like WhatsApp, facebook, Instagram, Twitter and to copy the link to clipboard.
The link needs to be edited by the owner in the respective card items please do check those

2024-10-12 18:49 UTC, Tejashri-Taral reviewed
Can you adjust it in below the product
![image](https://github.com/user-attachments/assets/8bd276e4-8773-4d8a-8b71-30c07a03fe15)

2024-10-13 03:26 UTC, KrishnaMohanty08 commented
ok i will be fixing it thanks for letting me know

2024-10-13 17:39 UTC, Tejashri-Taral approved these changes

2024-10-13 17:39 UTC, merged

2024-10-13 17:44 UTC, hars-21 requested changes
![image](https://github.com/user-attachments/assets/a3561dd1-f0fa-4d25-ada5-340f4e9df52b)

Please match the add to cart buttons width with the card. Also, see this minor alignment issue and add little more spacing to it.