add to wishlist
Tejashri-Taral/TrendTrove-Ecommerce pull request #512
Opened 2024-10-17 20:32 UTC by sanjuyadavvv

2024-10-19 16:34 UTC, hars-21 commented
@sanjuyadavvv  Please resolve the merge conflicts

2024-10-20 05:08 UTC, sanjuyadavvv commented
Fixed!

On Sat, 19 Oct 2024 at 10:05 PM, Harshil Gupta ***@***.***>
wrote:

> @sanjuyadavvv <https://github.com/sanjuyadavvv> Please resolve the merge
> conflicts
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Tejashri-Taral/TrendTrove-Ecommerce/pull/512#issuecomment-2424057797>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDSW6XQDHU3JQGK6DDVL5STZ4KC4JAVCNFSM6AAAAABQERPBD2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMRUGA2TONZZG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-20 18:09 UTC, hars-21 requested changes
![image](https://github.com/user-attachments/assets/08472418-3ab1-41df-9392-c01e906ed3e9)
 
Fix this and also fix padding in the add to wishlist button.

2024-10-24 11:46 UTC, Tejashri-Taral commented
Any update?

2024-10-25 15:53 UTC, closed without merging